### PR TITLE
Fix Source Command Repo Link and fix typo

### PR DESCRIPTION
**Pull request by NyCodeGHG**

### CODE REVIEW

**Comment by DRSchlaubi** [comment]
Let's merge that to develop because I won't make another release today

**Review by warriorzz — APPROVED** [review]

**Comment by warriorzz** [comment]
👍🏻

**Comment by NyCodeGHG** [comment]
warrior

**Comment by DRSchlaubi** [comment]
Should work now

**Review by DRSchlaubi — APPROVED** [review]

**Pull request merged**
