### PR TITLE
Update license to AGPL

### PR DESCRIPTION
**Pull request by NyCodeGHG**

### CODE REVIEW

**Comment by DRSchlaubi** [comment]
Why would we update to AGPL?

**Comment by NyCodeGHG** [comment]
Because there are some people which are yoinking our code without asking and just provide information in the info command that it is based on our code and I don't like that.

**Review by warriorzz — APPROVED** [review]

**Comment by DRSchlaubi** [comment]
AWSOME warrior just randomly approved it

**Comment by warriorzz** [comment]
not randomly :D

**Comment by warriorzz** [comment]
if we have resolved this conflict we can change it back if it isn't necessary

**Pull request merged**
